// <auto-generated />
using System;
using Anemone.Infrastructure.Persistence.HeatingSystemData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anemone.Repository.Migrations
{
    [DbContext(typeof(HeatingSystemContext))]
    [Migration("20230310081728_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Anemone.Repository.HeatingSystemData.HeatingSystem", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HeatingSystem");
                });

            modelBuilder.Entity("Anemone.Repository.HeatingSystemData.HeatingSystemPoint", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeatingSystemId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Inductance")
                        .HasColumnType("REAL");

                    b.Property<double>("Resistance")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TypeValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("HeatingSystemId");

                    b.ToTable("HeatingSystemPoint");
                });

            modelBuilder.Entity("Anemone.Repository.HeatingSystemData.HeatingSystemPoint", b =>
                {
                    b.HasOne("Anemone.Repository.HeatingSystemData.HeatingSystem", "HeatingSystem")
                        .WithMany("HeatingSystemPoints")
                        .HasForeignKey("HeatingSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeatingSystem");
                });

            modelBuilder.Entity("Anemone.Repository.HeatingSystemData.HeatingSystem", b =>
                {
                    b.Navigation("HeatingSystemPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
